name: "Main"

on:
  push:

jobs:
  build-quick:
    if: github.ref_type == 'branch'
    uses: ./.github/workflows/_build-wheel.yml
    with:
      runner: ubuntu-24.04
      platform: manylinux_2_17_x86_64
      upload_artifact: false
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      fail-fast: true
      matrix:
        include:
          - runner: macos-15
            platform: macosx_11_0_arm64
          - runner: macos-15-intel
            platform: macosx_10_9_x86_64
          - runner: ubuntu-24.04
            platform: manylinux_2_17_x86_64
          - runner: ubuntu-24.04
            platform: musllinux_1_2_x86_64
          - runner: ubuntu-24.04-arm
            platform: manylinux_2_17_aarch64
          - runner: ubuntu-24.04-arm
            platform: musllinux_1_2_aarch64
          - runner: windows-2025
            platform: win_amd64
          - runner: windows-11-arm
            platform: win_arm64
    uses: ./.github/workflows/_build-wheel.yml
    with:
      runner: ${{ matrix.runner }}
      platform: ${{ matrix.platform }}
      upload_artifact: true
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: Download all wheels
        uses: actions/download-artifact@v8
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true
      - name: Publish
        run: uv publish dist/*.whl
