name: "Main"

on:
  push:

jobs:
  build-quick:
    if: github.ref_type == 'branch'
    uses: ./.github/workflows/_build-wheel.yml
    with:
      runner: ubuntu-24.04
      platform: linux-amd64
      cgo: "1"
      upload_artifact: false
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      fail-fast: true
      matrix:
        include:
          - runner: macos-15
            platform: darwin-arm64
            cgo: "1"
          - runner: macos-15-intel
            platform: darwin-amd64
            cgo: "1"
          - runner: ubuntu-24.04
            platform: linux-amd64
            cgo: "1"
          - runner: ubuntu-24.04
            platform: linux-amd64-musl
            cgo: "0"
          - runner: ubuntu-24.04-arm
            platform: linux-arm64
            cgo: "1"
          - runner: ubuntu-24.04-arm
            platform: linux-arm64-musl
            cgo: "0"
          - runner: windows-2025
            platform: windows-amd64
            cgo: "1"
          - runner: windows-11-arm
            platform: windows-arm64
            cgo: "0"
    uses: ./.github/workflows/_build-wheel.yml
    with:
      runner: ${{ matrix.runner }}
      platform: ${{ matrix.platform }}
      cgo: ${{ matrix.cgo }}
      upload_artifact: true
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true
      - name: Publish
        run: uv publish dist/*.whl
